### PR TITLE
[RESTEASY-2136] Upgrade to SpringBoot 2.1.2.RELEASE

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by asoldano** [comment]
JIRA: https://issues.jboss.org/browse/RESTEASY-2136

**Comment by geoand** [comment]
> Shouldn't you be updating the springboot.version in sample-app/pom.xml and sample-app-no-jaxrs-application/pom.xml too?

Absolutely! I missed that - fixing now

**Comment by geoand** [comment]
@asoldano PR updated

**Comment by geoand** [comment]
> Thanks

You're welcome!

**Pull request merged**
