### PR TITLE
Remove Yasson with Resteasy version 3.6.2 from runtime deps

### PR DESCRIPTION
**Pull request by soberich**
Using something like Jackson, finally with 3.6.2 we a re able to remove unnecessary hanging Yasson.

### CODE REVIEW

**Comment by asoldano** [comment]
JIRA: https://issues.jboss.org/browse/RESTEASY-2137

**Comment by asoldano** [comment]
@geoand , would you mindquickly  testing this too with your environment / integration? I'm leaning towards merging this too before releasing.

**Comment by geoand** [comment]
@asoldano Sure, I check out the PR locally, rebase it onto the current master and run my integration

**Comment by asoldano** [comment]
@geoand thanks (yep, now there're conflicts here, feel free to open another PR of yours for this)

**Comment by geoand** [comment]
@asoldano Ah yes, I will do that

**Pull request closed without merging**
