### PR TITLE
Upgrade RestEasy to 3.7.0.Final

### PR DESCRIPTION
**Pull request by sharathsrinivasa**
Upgrade spring-boot to 2.1.5.RELEASE
Fix README files

### CODE REVIEW

**Comment by ronsigal** [comment]
@liweinan, to be honest, I don't know where the travis configurations live. Hint?

**Comment by fabiocarvalho777** [comment]
@ronsigal here it is: https://github.com/resteasy/resteasy-spring-boot/blob/master/.travis.yml

**Comment by ronsigal** [comment]
Ah, thanks, @fabiocarvalho777. I don't know what it means, but at least I have something to read. ;)

**Comment by liweinan** [comment]
@asoldano Does this project also need the contributors to agree the resteasy contributor agreement?

**Comment by liweinan** [comment]
@asoldano okay! Let me fix the tests and ask @sharathsrinivasa for agreement.

**Comment by liweinan** [comment]
I have created PR to fix the travisci build problem and merged it: https://github.com/resteasy/resteasy-spring-boot/pull/21

**Comment by liweinan** [comment]
@sharathsrinivasa The pr looks good. We require that all contributions be made under the terms of the ASL
2.0 License: http://www.apache.org/licenses/LICENSE-2.0
Do you agree to these terms?

**Comment by metacosm** [comment]
What are that plans regarding this PR? Will the starter be released soon after?

**Comment by asoldano** [comment]
Hi @metacosm . Considering the interest, yes I believe @liweinan can release soon after this PR is merged.

**Comment by sharathsrinivasa** [comment]
@liweinan Apologies for late reply. Computer was not accessible for me.

Aye, I agree ASL 2.0 license.

**Comment by metacosm** [comment]
Excellent! 🎊

**Pull request merged**
