### PR TITLE
resteasy 3.6.0.Final, springboot 2.0.3.RELEASE, openjdk10 pipeline

### PR DESCRIPTION
**Pull request by jens-meiss**
hi,

i updated the versions to the latest and greatest, i also enabled a jdk10 pipeline :)

i accept the terms of ASL 2.0 License (http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by asoldano** [comment]
@jens-meiss thanks for the PR.
Generally speaking, I think it's fine and I'm going to merge it soon. I'm not convinced about the version bump, I'd rather perform the upgrade to RESTEasy 3.6 series (as you did) and tag 2.0.0.Final, given 3.6 is basically the completion of 3.5 series. Would that be fine to you?

Thanks for the explicit agreement to the license, you're marked as a contributor already anyway, so we know you're ok with it :-)

**Comment by asoldano** [comment]
@jens-meiss sorry for the late reply, I've been on PTO and then catching up.
I've noticed that this PR basically fails passing testsuite if rebased against master. Can you please check that / fix?
As for the versioning , I've created https://issues.jboss.org/browse/RESTEASY-1972 , let's move to resteasy 3.6 series in 2.0.0, we're already jumping from 3.1.4, so 3.5 or 3.6 shouldn't be a big difference. After this upgrades are done, btw, I think we should release 2.0.0.Final.

**Comment by jens-meiss** [comment]
hi, i merged the master again, but for any reason the travis pipeline didn't get executed... may they have a problem atm ...

**Comment by asoldano** [comment]
@jens-meiss it has now run and it passed. Actually I've just found that I had a corrupted archive locally, sorry about that. I'll work on this later tonight.

**Comment by asoldano** [comment]
@jens-meiss , I've cherry-picked your first commit (basically the real changes, not the project version bump) in #6 and merged that. Thanks a lot. We'll soon be releasing.

**Pull request closed without merging**
