### PR TITLE
RESTEASY-2320 Bump RESTEasy and Spring Boot versions for 3.x

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by geoand** [comment]
@asoldano could we have this merged and released as `3.2.0.Final`?

**Comment by geoand** [comment]
@asoldano thanks for the quick reply!

We need `3.7.0.Final` since that is the version we are supposed to be relying on

**Comment by geoand** [comment]
For us, the sooner we have can this, the better :)

**Comment by liweinan** [comment]
work in progress

**Comment by liweinan** [comment]
travis fix: https://github.com/resteasy/resteasy-spring-boot/pull/25

**Comment by geoand** [comment]
@liweinan I rebased this PR onto the latest `3.x` branch

**Pull request merged**
