### PR TITLE
Can not integrate with spring doc #349

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
After this is fixed: https://github.com/resteasy/resteasy-spring-boot/pull/354

I can now run `springdoc` with the example by this PR:

- http://localhost:8080/sample-app/swagger-ui/index.html

image

In the next step, I'll update the README and add Swagger annotations to generate the API doc.

**Comment by liweinan** [comment]
image

**Comment by liweinan** [comment]
It seems I need to use the swagger generated openapi doc instead of the springdoc generated one(which is not correctly generated).

**Comment by liweinan** [comment]
todo: disable the broken generated doc in: http://localhost:8080/sample-app/v3/api-docs

**Comment by liweinan** [comment]
All the code work is done. And I plan to write a team blog post for this PR.

**Comment by thegenius** [comment]
great works

**Comment by liweinan** [comment]
@thegenius Glad it helps :D 

btw I started to write a blog post related to this PR:

- https://github.com/resteasy/resteasy.dev/pull/3

Which introduces multiple integration methods with OpenAPI.

If there is anything else that needs help feel free to ask.

**Pull request merged**
